### ISSUE TITLE
Toolbar Issue

### ISSUE THREAD

**Issue by gigocabrera** [jbw91/toolbar-issue#1]
@jbw91 I have a similar issue with the statusbar as you did (https://github.com/ionic-team/ionic/issues/13144) and I noticed you got it fixed. I followed every possible suggestion and even  compared your config.xml and package.json with mine and the only difference I see is 
that I'm using `"cordova-ios": "^4.5.2"`. This version of cordova ios was installed automatically when I added the ios platform.

Have you tried using the `cordova-ios": "^4.5.2` at all? 

Also, can you post your `ionic info`?

**Comment by johnbwoodruff** [comment]
Actually I haven't updated this repo with the fix. This repo was simply recreating my issue in my real app. I'll create a pull request that shows the steps I took to fix it, but basically I followed the steps in this article: http://blog.ionic.io/ios-11-checklist/

**Comment by johnbwoodruff** [comment]
@gigocabrera here is the pull request: https://github.com/jbw91/toolbar-issue/pull/2

**Comment by gigocabrera** [comment]
@jbw91 Thank you for the PR. One more favor if you don't mind. Can you post your `ionic info`

I will try to clone your repo to see if it works for me on my end.

**Comment by johnbwoodruff** [comment]
Sure thing:

```
cli packages: (/Users/john/dev/ionic/toolbar-issue/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    Node       : v7.10.1
    npm        : 5.4.2 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Misc:

    backend : pro
```
